### ISSUE TITLE
Pretrained gnt model install

### ISSUE THREAD

**Issue by lan-creator** [apple/ml-pgdvs#1]
Hello, I notice that there is a pretrained gnt model in your download_ckpts.sh like this:

if [ "${FLAG_ORIGINAL}" == "1" ]; then
    # GNT
    if [ ! -f ${DATA_ROOT}/gnt/generalized_model_720000.pth ]; then
        gdown 1AMN0diPeHvf2fw53IO5EE2Qp4os5SkoX -O ${DATA_ROOT}/gnt/
    fi 

However, I couldn't find this file on google drive and they tell me it not exist. How could I get this?
Thanks!

**Comment by Xiaoming-Zhao** [comment]
It seems like GNT's repo changes the link in [this commit](https://github.com/VITA-Group/GNT/commit/53e0fc3d39b4244503d6c4de1e34bbf3199dd2a8).

I am not sure whether the checkpoint in the new url is the same as what I used.

To align with the one I used before, you can download the checkpoint from [here](https://github.com/apple/ml-pgdvs/releases/tag/v0.1).

Hope this helps.

**Comment by lan-creator** [comment]
Oh thank you, this help me!
