### ISSUE TITLE
How can you make sure each pixel has its corresponding point cloud?

### ISSUE THREAD

**Issue by Loydian** [apple/ml-pgdvs#4]
I notice that you project the point cloud to the image plane for rendering. But how can you make sure each pixel has its corresponding point cloud? Are there any constrains?

**Comment by Xiaoming-Zhao** [comment]
We required consistent depth corresponding to each image, which will give us a per-pixel 3D point.

**Comment by Loydian** [comment]
But since the point clouds are filtered by a cycle consistent check, how do you inpaint the filtered points?
