### ISSUE TITLE
Nvidia Dataset eval code resize problem

### ISSUE THREAD

**Issue by lan-creator** [apple/ml-pgdvs#8]
Hello, I notice that in the NVIDIA evaluation we reset the resolution as below:

https://github.com/apple/ml-pgdvs/blob/ea52ac32076a4ceaf6631d3f098570f2de108d99/pgdvs/datasets/nvidia_eval.py#L403-L406

However, the intrinsics should also change with the image resolution. I wonder if there is some intrinsics change, which should refer to the focal. Thank you for your reply!

**Comment by Xiaoming-Zhao** [comment]
Yes, you are right.

The snippet you mentioned only modifies the height, width, and focal, which will change the intrinsic in the following snippet:
https://github.com/apple/ml-pgdvs/blob/ea52ac32076a4ceaf6631d3f098570f2de108d99/pgdvs/datasets/nvidia_eval.py#L814-L816

Hope this helps.

**Comment by lan-creator** [comment]
Yeah, I didn't notice this function and further check it, which really helps. Thank you for your reply!
https://github.com/apple/ml-pgdvs/blob/ea52ac32076a4ceaf6631d3f098570f2de108d99/pgdvs/datasets/nvidia_eval.py#L1013-L1030
